create table book(id int, name char(20), price float, primary key(id));
insert into book values (1, "NA", 1.2);
insert into book values (4, "OOp", 7.8);
insert into book values (15, "Eng", 12.2);
insert into book values (2, "BD", 5.4);
insert into book values (9, "Ode", 0.4);
insert into book values (11, "Ode", 299);
select * from book;
delete from book where id=4;
delete from book where id>10 and price >100;
select * from book;
insert into book values(12,"lp",108.0);
select * from book;
drop table book;